### ISSUE TITLE
fmtTimeSpan in Anki 2.1.21 was missing, then changed

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki__Deck_and_Card_Info_during_review#4]
Debug info:
Anki 2.1.21 (65ec9d19) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-02-25 07:37:01

Caught exception:
Traceback (most recent call last):
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\673114053\__init__.py", line 95, in cardStats
    cs.toggle()
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\673114053\sidebar_base.py", line 93, in toggle
    self.show()
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\673114053\sidebar_base.py", line 79, in show
    update_contents_of_sidebar(self)
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\673114053\sidebar_set_contents.py", line 27, in update_contents_of_sidebar
    p = current_card_deck_properties(card)
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\673114053\card_deck_properties.py", line 21, in current_card_deck_properties
    formatted_steps += ' -- ' + fmtTimeSpan(i * 60, short=True)
TypeError: fmtTimeSpan() got an unexpected keyword argument 'short'

**Comment by ijgnd** [comment]
Thanks for the report. I will adjust the code soon.

At least the error message should be fixed in anki beta three because of [add missing short argument to legacy fmtTimeSpan()](https://github.com/ankitects/anki/commit/cfe4af81cfc3e14f55b4ac11181ce714585611bf) but it might not look good.

**Comment by ghost** [comment]
I see. Thank you for the information.

**Comment by ghost** [comment]
Working as of beta 3. Thanks.

**Comment by ijgnd** [comment]
I'll leave this open as a reminder for me because the hhmm part makes the line to wide for me
